# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r6_TkqTGiUAowuSwE_9tFu8Bt_Bs2ILu
"""

def quicksort(list, left, right):                                               #定義輸入陣列和
  if left >= right:                                                             #如果左邊>右邊，跳出程序
    return
  i = left                                                                      #左指標
  j = right                                                                     #右指標
  pivot = list[left]                                                            #基準點
  while i != j:
    while list[j] > pivot and i < j:                                            #從右邊開始找，找比基準點小的值
      j -= 1
    while list[i] <= pivot and i < j:                                           #從左邊開始找，找比基準點大的值
      i += 1
    if i < j:                                                                   #當左右指標沒有遇到，互換值
      list[i], list[j] = list[j], list[i]
    
  list[left] = list[i]                                                          #將基準點煥至左右指標相遇的點
  list[i] = pivot

  quicksort(list, left, i-1)                                                    #將新基準點左邊及右邊也重複做一次quicksort
  quicksort(list, i+1, right)

list = [33, 67, 8, 13, 54, 119, 3, 84, 25, 41]                                  #輸入要排序的值
quicksort(list, 0, len(list)-1)
print(list)